name: Terraform Workflow

on:
  push:
    branches:
      - main  # Defina a branch na qual deseja acionar o fluxo de trabalho

jobs:
  terraform:
    runs-on: ubuntu-latest  # Utilize o sistema operacional desejado para o fluxo de trabalho

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 3.59.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan


